twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : nav_vel
        timeout : 0.5
        priority: 10
        # stamped : false
        stamped : true

      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 100
        # stamped : false
        stamped : true

      keyboard:
        topic   : cmd_vel
        timeout : 0.5
        priority: 50
        stamped : false
        # stamped : true
